# Generated by Django 4.1 on 2024-01-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_salesitems_date_added_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='branch_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleitembranch', to='posApp.branch'),
        ),
    ]
