# Generated by Django 4.1 on 2024-01-25 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_salesitems_branch_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='user',
            field=models.ManyToManyField(null=True, related_name='branchusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
