# Generated by Django 4.1 on 2024-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_alter_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
